/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      spacing: {
        1: '4px', 2: '8px', 3: '12px', 4: '16px', 5: '20px',
        6: '24px', 8: '32px', 10: '40px', 11: '44px', 12: '48px',
        16: '64px', 20: '80px', 24: '96px',
        sidebar: '256px',
      },
      screens: {
        xs: '425px',
        sm: '600px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1600px',
      },
      colors: {
        canvas: 'var(--color-canvas)',
        workspace: 'var(--color-workspace)',
        surface: 'var(--color-surface)',
        'surface-subtle': 'var(--color-surface-subtle)',
        'surface-strong': 'var(--color-surface-strong)',
        editor: 'var(--color-editor)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        action: 'var(--color-action)',
        'action-hover': 'var(--color-action-hover)',
        'action-tint': 'var(--color-action-tint)',
        link: 'var(--color-link)',
        'on-action': 'var(--color-on-action)',
        hairline: 'var(--color-hairline)',
        'border-strong': 'var(--color-border-strong)',
        focus: 'var(--color-focus)',
        selection: 'var(--color-selection)',
        success: 'var(--color-success)',
        'success-surface': 'var(--color-success-surface)',
        'success-border': 'var(--color-success-border)',
        warning: 'var(--color-warning)',
        'warning-surface': 'var(--color-warning-surface)',
        'warning-border': 'var(--color-warning-border)',
        error: 'var(--color-error)',
        'error-surface': 'var(--color-error-surface)',
        'error-border': 'var(--color-error-border)',
        info: 'var(--color-info)',
        'info-surface': 'var(--color-info-surface)',
        'info-border': 'var(--color-info-border)',
      },
      borderRadius: {
        workspace: 'var(--radius-workspace)',
        panel: 'var(--radius-panel)',
        control: 'var(--radius-control)',
        compact: 'var(--radius-compact)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        workspace: 'var(--shadow-workspace)',
        floating: 'var(--shadow-floating)',
      },
      fontFamily: {
        sans: ['var(--font-text)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'page-title': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'section-title': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'control': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'metadata': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'technical': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        // Landing display ramp (Elevated Civic): hero and section openers only.
        'display-hero': [
          'clamp(2.5rem, 1rem + 5vw, 3.75rem)',
          { lineHeight: '1.15', fontWeight: '700' },
        ],
        'display-lg': [
          'clamp(2rem, 0.875rem + 3.6vw, 2.75rem)',
          { lineHeight: '1.18', fontWeight: '700' },
        ],
        'display-md': [
          'clamp(1.625rem, 1rem + 2vw, 2.125rem)',
          { lineHeight: '1.22', fontWeight: '700' },
        ],
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        standard: 'var(--duration-standard)',
        emphasized: 'var(--duration-emphasized)',
      },
      transitionTimingFunction: {
        product: 'var(--ease-out)',
        decelerate: 'var(--ease-decelerate)',
        spring: 'var(--ease-spring)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        backdrop: 'var(--z-backdrop)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        toast: 'var(--z-toast)',
      },
    },
  },
  plugins: [],
};
