#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "$0")/.."
ENV_FILE="${ENV_FILE:-.env.cutover.local}"
TOTAL_STAGES=9

banner "DocAI free-tier production cutover"

stage "Preflight and main commit"
say "Production comes only from a clean, green origin/main commit."
command -v git >/dev/null || { warn "git is required"; exit 1; }
git fetch origin main
[[ "$(git branch --show-current)" == "main" ]] || { warn "Check out main before cutover."; exit 1; }
git diff --quiet && git diff --cached --quiet || { warn "The checkout is dirty."; exit 1; }
MAIN_SHA="$(git rev-parse HEAD)"
[[ "$MAIN_SHA" == "$(git rev-parse origin/main)" ]] || { warn "Local main is not the exact origin/main commit."; exit 1; }
write_env MAIN_SHA "$MAIN_SHA"
step "Run the full repository verifier: pwsh ./ops/verify-all.ps1"
pwsh ./ops/verify-all.ps1
step "Run the offline conversion release render gate."
python ./conversion-service/eval/verify_p0a.py
confirm "Are CI checks green for $MAIN_SHA?" || { warn "Green CI is required."; exit 1; }

stage "Free-tier accounts"
say "This cutover creates no paid compute. Paid fallback requires a new decision."
open_url "https://cloud.oracle.com/limits"
step "OCI: confirm the tenancy is Free Tier and the home region is correct."
step "OCI: confirm Always Free A1 and block-volume capacity is still unused."
open_url "https://console.cloud.google.com/billing"
step "GCP: confirm billing is active for free-tier GCS and uptime checks; set a small alert budget."
open_url "https://dash.cloudflare.com/"
step "Cloudflare: confirm the domain is active and Workers stays on Free."
confirm "Is MFA enabled on OCI, GCP, Cloudflare, and GitHub?" || { warn "Enable MFA first."; exit 1; }

stage "Domain, policy, and secrets"
ask DOMAIN "Production root domain (example.com):"
[[ "$DOMAIN" =~ ^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]] || { warn "Enter a real root domain."; exit 1; }
API_DOMAIN="api.$DOMAIN"
APP_ORIGIN="https://app.$DOMAIN"
BACKEND_API_URL="https://$API_DOMAIN"
CORS_ORIGIN="$APP_ORIGIN"
ask PUBLIC_SUPPORT_EMAIL "Working support email on this domain:"
[[ "$PUBLIC_SUPPORT_EMAIL" == *@"$DOMAIN" ]] || { warn "Use a working address on $DOMAIN."; exit 1; }
write_env DOMAIN "$DOMAIN"
write_env API_DOMAIN "$API_DOMAIN"
write_env APP_ORIGIN "$APP_ORIGIN"
write_env BACKEND_API_URL "$BACKEND_API_URL"
write_env PUBLIC_SUPPORT_EMAIL "$PUBLIC_SUPPORT_EMAIL"
write_env PUBLIC_POLICY_EFFECTIVE_DATE "2026-08-31"
say "Public policy values: DocAI · Vietnam · effective 2026-08-31."
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Create a hostname-restricted Turnstile widget for app.$DOMAIN."
step "Put its site key in the Worker dashboard and its secret key only in backend/.env on the VM."
step "Generate DB_PASSWORD, JWT_SECRET, and LLM_CONFIG_ENCRYPTION_KEY in your password manager."
step "Store the encryption key in an offline password-manager entry; losing it destroys all saved BYOK keys."
confirm "Are every production secret and the recovery key stored in the password manager?" || exit 1

stage "Oracle Always Free VM"
open_url "https://cloud.oracle.com/compute/instances"
step "Create VM.Standard.A1.Flex in the tenancy home region with exactly 2 OCPU / 12 GB and Ubuntu ARM64."
step "Use a 100 GB Always Free boot volume and open inbound TCP 22, 80, and 443 only."
warn "If OCI reports 'out of host capacity', try another availability domain or later; stop the cutover."
warn "Oracle may reclaim an idle Always Free VM. Do not create fake traffic; backups make the VM replaceable."
confirm "Is the A1 VM running and labeled Always Free?" || { warn "No suitable free VM means no cutover."; exit 1; }
ask VM_SSH "SSH target (for example ubuntu@203.0.113.10):"
[[ "$VM_SSH" =~ ^[A-Za-z0-9._-]+@[A-Za-z0-9.:_-]+$ ]] || { warn "Invalid SSH target."; exit 1; }
write_env VM_SSH "$VM_SSH"
ask DEPLOY_DIR "Empty deployment directory [Enter = /opt/conversion-service-standalone]:"
DEPLOY_DIR="${DEPLOY_DIR:-/opt/conversion-service-standalone}"
[[ "$DEPLOY_DIR" =~ ^/[A-Za-z0-9._/-]+$ ]] || { warn "DEPLOY_DIR must be an absolute simple path."; exit 1; }
write_env DEPLOY_DIR "$DEPLOY_DIR"
step "Install Docker Engine, the Compose plugin, git, age, OCI CLI, gcloud CLI, and Python 3."
step "Configure a read-only GitHub deploy key, then clone origin/main into this empty directory: $DEPLOY_DIR"
step "Create mode-600 .env and backend/.env from the examples; enter secrets directly on the VM."
step "Set API_DOMAIN=$API_DOMAIN, CORS_ORIGIN=$CORS_ORIGIN, open registration, Turnstile, queue depth 100, and quota 50."
ssh -o BatchMode=yes -o ConnectTimeout=10 "$VM_SSH" true || { warn "SSH connectivity failed."; exit 1; }
confirm "Is the repository cloned into the empty directory and are both VM env files mode 600?" || exit 1

stage "Cloudflare Worker"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Create a Worker from the Git repository; production branch must be main and root directory frontend."
step "Build command: npm ci && npm run build:worker. Deploy command: npx wrangler deploy."
step "Set BACKEND_API_URL=$BACKEND_API_URL and all PUBLIC_* values as production variables."
step "Set Turnstile site key, open-registration flag, secure-cookie flag, and trust-proxy count as production variables."
step "Add app.$DOMAIN as the Worker custom domain. Add api.$DOMAIN to the VM and keep it DNS-only for Caddy ACME."
confirm "Did the Worker deploy the exact main commit and pass /api/live?" || exit 1

stage "Encrypted GCS backup"
open_url "https://console.cloud.google.com/storage/browser"
step "Create a regional bucket in us-central1, us-east1, or us-west1; keep total backup storage under the 5 GB free allowance."
step "Create a least-privilege service account that can write/delete objects only in this bucket."
step "Set a lifecycle rule that deletes objects after 30 days."
step "Generate the age identity offline; put only AGE_RECIPIENT on the VM and keep the identity in the password manager."
step "Install the nightly timer for ops/backup/postgres-dump.sh and ops/backup/sync-to-gcs.sh."
confirm "Does the bucket contain a non-empty .pgdump.age object and no plaintext dump?" || exit 1

stage "Monitoring and email alerts"
open_url "https://cloud.oracle.com/monitoring/alarms"
step "Enable instance-principal permission for OCI custom metrics in namespace docai."
step "Install collect-health.sh and publish-oci-metrics.sh on a five-minute systemd timer."
step "Create email alarms: queue >=80/10m, disk >=80%/15m, backup age >=129600s, unhealthy containers >=1/5m."
open_url "https://console.cloud.google.com/monitoring/uptime"
step "Create GCP uptime checks for $APP_ORIGIN/api/live and $BACKEND_API_URL/health."
step "Confirm the OCI notification subscription and deliberately trigger one test email."
confirm "Did the test alert arrive at the owner's real email address?" || exit 1

stage "Deploy exact main commit"
say "The deploy helper may roll application containers back, but it never restores a database or deletes a volume."
step "On the VM, fetch origin/main and verify $MAIN_SHA is the current origin/main commit."
if confirm "Run the production deploy helper over SSH now?"; then
  ssh "$VM_SSH" "cd '$DEPLOY_DIR' && API_DOMAIN='$API_DOMAIN' APP_ORIGIN='$APP_ORIGIN' ./ops/deploy-production.sh '$MAIN_SHA'"
else
  warn "Deployment is still pending. Use the exact command in docs/runbook.md §6.3."
  exit 1
fi
curl -fsS --max-time 15 "$APP_ORIGIN/api/ready" >/dev/null || { warn "Frontend readiness failed."; exit 1; }
curl -fsS --max-time 15 "$BACKEND_API_URL/health" >/dev/null || { warn "API health failed."; exit 1; }

stage "Soft-launch gate"
say "Keep registration open behind Turnstile, but do not advertise the URL for 48 hours."
step "Run conversion-service/eval/preflight.py in the production conversion container."
ssh "$VM_SSH" "cd '$DEPLOY_DIR' && docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T conversion python eval/preflight.py --url http://127.0.0.1:8004"
step "Run conversion-service/CUTOVER_CHECKLIST.md and record the exact main SHA."
step "Upload a real digital PDF, a scan with BYOK Gemini, a legacy Vietnamese fixture, and a file larger than 4.5 MB."
step "Verify per-file partial failure, five-second polling, queue-busy handling, download, fidelity report, and account deletion."
step "Perform one scratch restore from the encrypted GCS object and record counts."
step "Observe Cloudflare errors, OCI alarms, disk, backup age, queue depth, and container health for 48 hours."
confirm "Have all checks passed and has the full 48-hour quiet observation completed?" || { warn "Stay in soft launch and rerun this stage later."; exit 1; }

finish
note "Free-tier production is live on $MAIN_SHA. Keep the VM rebuild path and encrypted backup key available."
